[build]
  ignore = "exit 0"
  # base = "."
  # command = "npm run build"
  # functions = "dist/hosting/netlify/functions"
  # publish = "dist/hosting/netlify/public"

[dev]
  command = "npx nx build web-astro:dev"
  port = 3000
  autoLaunch = false

[functions."aggregate"]
schedule = "@hourly"

[functions."maintenance"]
schedule = "@hourly"

[[redirects]]
  from = "https://pdcstrrss.netlify.app/*"
  to = "https://pdcstrrss.app/:splat"

[[redirects]]
  from = "/js/stats.js"
  to = "https://plausible.io/js/script.js"
  status = 200

[[redirects]]
  from = "/stats/event"
  to = "https://plausible.io/api/event"
  status = 200

[[redirects]]
  from = "/api/aggregate"
  to = "/.netlify/functions/function-aggregate"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
