[build]
  command = "remix build"
  functions = "netlify/functions"
  publish = "public"
  node_bundler = "esbuild"

[dev]
  command = "remix watch"
  port = 3000
  autoLaunch = false

[[redirects]]
  from = "/js/stats.js"
  to = "https://plausible.io/js/script.js"
  status = 200

[[redirects]]
  from = "/stats/event"
  to = "https://plausible.io/api/event"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[functions."aggregate"]
schedule = "@hourly"
