name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  workspace:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GH_OAUTH_CLIENT_ID: ${{ secrets.GH_OAUTH_CLIENT_ID }}
      GH_OAUTH_CLIENT_SECRET: ${{ secrets.GH_OAUTH_CLIENT_SECRET }}
      BASE_URL: ${{ secrets.BASE_URL }}
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: nrwl/nx-set-shas@v2
      - uses: bahmutov/npm-install@v1
      - run: npm run generate
      - run: npm run typecheck
      - run: npm run lint
      - run: npm run test
      - run: npm run build

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            apps/web-remix/public
            apps/web-remix/netlify
          retention-days: 1

  deploy:
    name: Publish to Netlify
    runs-on: ubuntu-latest
    needs: workspace
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: bahmutov/npm-install@v1
        env:
          NODE_ENV: production

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: apps/web-remix

      - name: Deploy production to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          production-branch: main
          production-deploy: true
          publish-dir: ./apps/web-remix/public
          functions-dir: ./apps/web-remix/netlify/functions
          netlify-config-path: ./apps/web-remix/netlify.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

